### ISSUE TITLE
About getting key error in foolowing command

### ISSUE THREAD

**Issue by bundelesneha05** [henriquebastos/python-decouple#54]
I am getting key error in following command ...what is the alternative option for it..or else how should correct it ??
import os
COMPUTER_NAME = os.environ['COMPUTERNAME']
print("Computer: ", COMPUTER_NAME)

**Comment by 0xC4N1** [comment]
os.environ is part of os, not of python-decouple. However chances are there is no `COMPUTERNAME` variable in your environment. To set it to None instead use `os.environ.get('COMPUTERNAME')`.

Hint: python-decouple supports environment variables as well. Since version 3 it overrides the configurations from config files by default if an environment variable with the same name exist.
```
from decouple import config
config('COMPUTERNAME', default=None)
```
