### ISSUE TITLE
UTF-8 support in .env

### ISSUE THREAD

**Issue by DimaDK24** [henriquebastos/python-decouple#62]
Hi, first of all, thanks for nice library! It's awesome software 👍 
I need to use UTF-8 in .env and want to use python-decouple for this, but I suppose it won't work with UTF-8, because it doesn't pass encoding param to open function:
https://github.com/henriquebastos/python-decouple/blob/24cc51c7880b79d81b5a75c2d441a41428792aa6/decouple.py#L125
So it will fallback to locale.getpreferredencoding(), as specified in Python docs, which is platform dependent. On my Windows 10 its cp1251, but I want to write UTF-8 in .env and be sure it will be read correctly by python-decouple.
It would be nice, if we could pass encoding kwarg to config() and it will be used in open() (or default if this kwarg is not specified)
Feel free to notify me, if I can help with something

**Comment by henriquebastos** [comment]
This seems nice. Can you propose a PR adding a default argument to config to do the trick?

**Comment by DimaDK24** [comment]
Sure, I'll do it in few days

**Comment by farzbood** [comment]
Hi Guys,
Since you're working on "Encoding", I've a concern on retrieving data from a UTF-8 .env file containing some "Persian/Farsi" string/text. When I get it back by "config()' it turns to another "charset/codpage", I tried to type the text in different editors, but the result is the same. FYI hereby is the original and retrieved values.It would be nice to let me know what's going on. Tnx
Code:config('COMPANY_NAME', default='ایده پردازان ارتباطات نوین')
.env:COMPANY_NAME=ایده پردازان ارتباطات نوین
Original:ایده پردازان ارتباطات نوین
Retrieved by config():'Ø§ÛŒØ¯Ù‡ Ù¾Ø±Ø¯Ø§Ø²Ø§Ù† Ø§Ø±ØªØ¨Ø§Ø·Ø§Øª Ù†ÙˆÛŒÙ†'

**Comment by DimaDK24** [comment]
Hi, @farzbood, look like this issue is quite stale. I proposed PR more than year ago (now I see it's completely not ideal and should be updated), and there're no more updates on this

**Comment by farzbood** [comment]
Yeah, I visit that. I will try to contact the owner too.
Thank you for response though.
good Luck

**Comment by farzbood** [comment]
Great! It works perfectly nice.
Thank You.
Peace V
